---

- name: ORACLE_EXPORTER | Replace default metrics by custom metrics 
  copy:
    src: "{{ oracle_exporter_custom_metrics_path }}"
    dest: "{{ oracle_exporter_default_metrics }}"
    owner: "{{ oracle_exporter_user }}"
    group: "{{ oracle_exporter_group }}"
    mode: 0664
  notify: restart oracle_exporter
  when: oracle_exporter_custom_metrics_path is defined
