---

- name: ORACLE_EXPORTER | Copy Daemon script
  template:
    src: oracledb_exporter.service.j2
    dest: /etc/systemd/system/oracledb_exporter.service
    mode: 0644
  notify: restart oracle_exporter

- name: ORACLE_EXPORTER | Configuring service
  systemd:
    name: oracledb_exporter
    state: "{{ oracle_exporter_service_state }}"
    enabled: "{{ oracle_exporter_service_enabled }}"
    daemon_reload: yes