---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: oracle_database
    groups:
      - oracle_database_group
    image: wnameless/oracle-xe-11g-r2:latest
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - '/tmp'
    stop_signal: 'RTMIN+3'
    networks:
      - name: oracle_network
        links:
        - oracle_exporter:oracle_exporter
    exposed_ports:
      - 1521/tcp
    published_ports:
      - 0.0.0.0:1521:1521/tcp
    pre_build_image: true
    override_command: false

  - name: oracle_exporter
    groups:
      - oracle_exporter_group
    image: ${MOLECULE_DISTRO:-debian:buster-slim}
    privileged: false
    capabilities:
      - SYS_ADMIN
    tmpfs:
      - /tmp
      - /run
      - /run/lock
    volumes:
      - '/sys/fs/cgroup:/sys/fs/cgroup:ro'
    command: '/lib/systemd/systemd'
    stop_signal: 'RTMIN+3'
    networks:
      - name: oracle_network
        links:
        - oracle_database:oracle_database
    exposed_ports:
      - 9161/tcp
    published_ports:
      - 0.0.0.0:9161:9161/tcp
provisioner:
  name: ansible
  lint:
    name: ansible-lint
verifier:
  name: goss
  lint:
    name: yamllint
